### ISSUE TITLE
Document new 3.0 features

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#4943]
Already implemented features:
* [x] errmessage on access policies (#4529)
  * https://github.com/edgedb/edgedb/pull/5220
* [x] UUID to object cast (#4469)
  * https://github.com/edgedb/edgedb/pull/5176
* [x] `json_object_pack` (#4474)
  * https://github.com/edgedb/edgedb/pull/5154
* [x] `EXCEPT` and `INTERSECT` (#4631)
  * https://github.com/edgedb/edgedb/pull/5155
* [x] Tuples in query arguments (#4489)
  * https://github.com/edgedb/edgedb/pull/5178
* [x] `MIGRATION REWRITE` (#4585)
  * https://github.com/edgedb/edgedb/pull/5290
* [x] `edgedb migration edit` (2.1)
  * https://www.edgedb.com/docs/cli/edgedb_migration/edgedb_migration_edit
* [x] `RESET SCHEMA TO initial` (#4714)
  * https://github.com/edgedb/edgedb/pull/5291
* [x] Nested modules (#4914)
  * https://github.com/edgedb/edgedb/pull/5153
* [x] The `assert` function (#5040)
  * https://github.com/edgedb/edgedb/pull/5237
* [x] SDL syntax changes: just the "Updates to SDL" part of https://github.com/edgedb/rfcs/blob/master/text/1022-freetypes.rst (#4983)
  * https://github.com/edgedb/edgedb/pull/5217
* [x] Shape splats ([RFC 1023](https://github.com/edgedb/rfcs/blob/master/text/1023-splats.rst), #5080)
  * https://github.com/edgedb/edgedb/pull/5152
* [x] Mutation rewrites: https://github.com/edgedb/rfcs/blob/master/text/1021-rewrites.rst (#4937)
  * https://github.com/edgedb/edgedb/pull/5324
* [x] Triggers: https://github.com/edgedb/rfcs/blob/master/text/1020-triggers.rst (but not `AFTER COMMIT OF`)
  * https://github.com/edgedb/edgedb/pull/5157
* [x] Link properties on computed backlinks (#5227)
  * https://github.com/edgedb/edgedb/pull/5292
* [x] Indexes: https://github.com/edgedb/rfcs/blob/master/text/1017-abstract-index.rst, https://github.com/edgedb/rfcs/blob/master/text/1018-extending-indexes.rst
  * https://github.com/edgedb/edgedb/pull/5430
* [ ] New CLI features
  * Documentation for any of these that are not already released (like `edgedb info --get`) probably shouldn't be merged/deployed until final 3.0 release since the CLI docs are non-versioned. I will continue working on them and submit draft pull requests so they don't get merged before release and cause confusion. (We probably need some way to handle CLI documentation against server versions so things like this can go out alongside other documentation.)
  * [ ] edgedb watch
    * https://github.com/edgedb/edgedb/pull/5342
  * [ ] edgedb migrate --dev-mode
  * [ ] edgedb migration upgrade-check
  * [ ] edgedb migration create --squash
  * [ ] edgedb analyze, \analyze, --expand
  * [ ] edgedb info --get (2.1)
  * [ ] --channel=testing, --to-testing in instance create, project init and cli upgrade
  * [ ] \d object xxx -> \d xxx maybe worth mentioning?

Delayed:
* ~~Full text search: https://github.com/edgedb/rfcs/blob/master/text/1015-full-text-search.rst~~

I'm sure I'm missing some here. @raddevon, could you take point here?

**Comment by raddevon** [comment]
@msullivan I notice `edgedb migration edit` is on this list, but it already has documentation: https://www.edgedb.com/docs/cli/edgedb_migration/edgedb_migration_edit

Is there a new change as part of 3.0 that needs to be documented, or does the existing documentation still work?
