### ISSUE TITLE
Query performance observability

### ISSUE THREAD

**Issue by msullivan** [edgedb/edgedb#7725]
Mostly a placeholder issue for now.
We want to provide visibility into query performance

I think the overall plan here is to use `pg_stat_statements` (https://www.postgresql.org/docs/current/pgstatstatements.html) to collect information.

I think the core questions are:

1. How do we connect our EdgeQL queries with information from pg_stat_statments?

   We forked pg_stat_statements to record custom information like EdgeQL query string, compilation settings, etc.

2. How do we expose the information to our users?

   `sys::QueryStats` is added as a view of the `pg_stat_statements` backend view.

- [x] Add edb_stat_statements (#7869)
- [x] Fix CI build (edgedb/edgedb-pkg#124)
- [x] Add config to turn off stats (#8033)
- [x] [Add `tag` to identify the source of queries](https://github.com/edgedb/edgedb/pull/7869#issuecomment-2471526873) (#8036)
- [x] Set query tag in CLI (edgedb/edgedb-cli#1408)
- [x] Set query tag in edgedb-python (edgedb/edgedb-python#552)
- [ ] Set query tag in edgedb-js (edgedb/edgedb-js#1133)

**Comment by fantix** [comment]
Closing as fixed, please see each linked PR for details.
